<?php

$content_node[1] = array(
  'title' => 'Tour del mes',
  'body' => '<p>La elección de Vietnam como la primera parada en su tour de Indochina con una larga visita a Hanoi, Halong, Danang, Saigón y el delta del Mekong, este tour le ofrece una vista panorámica de la encantadora Vietnam. Inicio de la vibrante pero tradicional ciudad de Hanoi, la elegante mezcla de belleza oriental, colonial y retro, que explorará la estructura diversificada de Hanoi y sus famosas 36 calles del casco antiguo por un viaje combinado que incluye caminar y tomar un paseo en un ciclo de tres ruedas. Tener una noche en un barco tradicional y elegante y disfrutar de la increíble vista de la bahía de Halong.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pulvinar suscipit nunc eget egestas. Suspendisse commodo pellentesque turpis sit amet euismod. Nam turpis erat, viverra nec mattis quis, semper ut lacus. Praesent at vulputate turpis, id fermentum risus. Ut ac erat risus. Aenean eleifend neque at rhoncus tincidunt. Nunc id orci odio. Phasellus id fringilla mauris, vitae tincidunt quam.</p>
<p>Cras cursus libero et accumsan placerat. Phasellus non enim tristique, porta metus ac, elementum diam. Nunc facilisis ut felis eu luctus. Morbi quis elit et enim aliquet pharetra et ac tellus. Vivamus pulvinar adipiscing orci quis semper. Fusce imperdiet purus eget erat hendrerit scelerisque. Quisque ac tortor ut lacus egestas fringilla. Ut tincidunt malesuada nulla, et ultrices purus malesuada ut.</p>
<p>Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mauris sapien, porta et semper id, tincidunt ut est. Praesent a lacus ac nisi consequat varius sagittis at justo. Aenean non neque et diam vestibulum elementum. Quisque suscipit diam erat, vel tempus augue pellentesque a. Suspendisse sit amet dui elit. Quisque volutpat cursus laoreet. Fusce euismod arcu ac est consectetur ultricies at quis tellus. Duis diam ante, bibendum iaculis sapien ac, faucibus pulvinar velit. Vestibulum non leo quis est imperdiet semper. Curabitur nunc mi, lacinia id fringilla vitae, pharetra non tellus. Vivamus nisi libero, placerat vitae est at, sollicitudin vestibulum diam.</p>',
  'summary' => 'La elección de Vietnam como la primera parada en su tour de Indochina con una larga visita a Hanoi, Halong, Danang,...',
  'format' => 'full_html',
  'image' => 'img01.jpg',
);

$content_node[2] = array(
  'title' => 'Tours a medida',
  'body' => '<p>Nuestros tours a medida son en realidad  diseñamos cada una específicamente adapatados a sus necesidades. Como sabemos que cada persona es un individuo y cada viaje debe ser tan individual como usted .  Así que hable de lo que usted busca con los expertos de viaje para diseñar tu próximo viaje juntos.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pulvinar suscipit nunc eget egestas. Suspendisse commodo pellentesque turpis sit amet euismod. Nam turpis erat, viverra nec mattis quis, semper ut lacus. Praesent at vulputate turpis, id fermentum risus. Ut ac erat risus. Aenean eleifend neque at rhoncus tincidunt. Nunc id orci odio. Phasellus id fringilla mauris, vitae tincidunt quam.</p>
<p>Cras cursus libero et accumsan placerat. Phasellus non enim tristique, porta metus ac, elementum diam. Nunc facilisis ut felis eu luctus. Morbi quis elit et enim aliquet pharetra et ac tellus. Vivamus pulvinar adipiscing orci quis semper. Fusce imperdiet purus eget erat hendrerit scelerisque. Quisque ac tortor ut lacus egestas fringilla. Ut tincidunt malesuada nulla, et ultrices purus malesuada ut.</p>
<p>Nulla facilisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur mauris sapien, porta et semper id, tincidunt ut est. Praesent a lacus ac nisi consequat varius sagittis at justo. Aenean non neque et diam vestibulum elementum. Quisque suscipit diam erat, vel tempus augue pellentesque a. Suspendisse sit amet dui elit. Quisque volutpat cursus laoreet. Fusce euismod arcu ac est consectetur ultricies at quis tellus. Duis diam ante, bibendum iaculis sapien ac, faucibus pulvinar velit. Vestibulum non leo quis est imperdiet semper. Curabitur nunc mi, lacinia id fringilla vitae, pharetra non tellus. Vivamus nisi libero, placerat vitae est at, sollicitudin vestibulum diam.</p></p>',
  'summary' => 'Nuestros tours a medida son en realidad  diseñamos cada una específicamente adapatados a sus necesidades...',
  'image' => 'img02.jpg',
);

$content_node[3] = array(
  'title' => 'Expertos en viajes',
  'body' => '<p>Nuestros expertos en viajes ofrecen  sus propias experiencias y conocimientos  en cada destino, no se trata sólo de visitar estas áreas, de  vivir allí. Nuestros expertos en viajes le aconsejan diseñado exclusivamente para usted, sus necesidades y deseos individuales, para que su próximo viaje sea perfecto para usted .</p>

<p>Cada uno de nuestros expertos en viajes se preocupa por sus viajes y la planificación con gran detalle, a sabiendas de lo que le gusta y lo que le importa. Así es como diseñamos específicamente su viaje.  Le ayudamos a elegir el alojamiento adecuado , marcando el ritmo adecuado de los viajes que le llevará donde quiera ir . Incluso si usted no sabe que existe todavía!</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in risus sed urna sollicitudin tincidunt ut vitae sapien. Duis aliquam magna at velit adipiscing, vel lobortis lorem bibendum. In rhoncus diam hendrerit accumsan tristique. Curabitur lobortis laoreet ligula quis varius. Vestibulum euismod egestas orci, quis venenatis arcu fringilla in. Suspendisse viverra, risus sed hendrerit adipiscing, ipsum justo commodo risus, vel tincidunt ante nunc ac orci. Morbi pharetra, dui eu fringilla luctus, diam diam semper nulla, ac suscipit dui nisi id odio. Cras fermentum nibh vel lacinia bibendum. Maecenas ornare ultricies ullamcorper. Suspendisse scelerisque vel elit at pulvinar. Nullam aliquet felis neque, quis vulputate augue malesuada ac. Proin lacinia lacus commodo mauris ornare ultrices id sit amet sapien. Aliquam vehicula in risus eget dictum. Sed euismod risus vitae adipiscing tincidunt. Proin ac nisi nulla.</p>
<p>Ut vel orci vel ligula posuere faucibus quis eu odio. Morbi a magna in purus iaculis molestie ac bibendum nibh. In et interdum urna, at scelerisque lectus. Etiam rutrum hendrerit enim. Nulla a augue dignissim, elementum nisi in, eleifend ante. Sed lacus nisi, condimentum ac erat at, ultrices consectetur felis. Suspendisse potenti. In feugiat vehicula facilisis. Aenean in ullamcorper tellus, id pellentesque libero. Nullam aliquam consectetur sapien. Nulla facilisi.</p>
<p>Sed et augue eu lectus dictum adipiscing. In eu nunc nisi. Nunc in libero ante. Sed lobortis eleifend risus eu venenatis. Aenean ultricies porttitor pharetra. Ut auctor sed mauris aliquet ultrices. Praesent euismod, justo ac cursus sagittis, nisi eros faucibus nisl, eu molestie tellus eros sit amet velit. Fusce at mauris in mi scelerisque iaculis. Proin dapibus rutrum ante, et laoreet justo euismod et. Etiam euismod adipiscing dapibus. Aliquam sollicitudin nulla nibh, sit amet blandit urna aliquam ac. Cras hendrerit risus massa, in faucibus eros ultrices quis. Proin eget leo nunc. Cras dictum elit a metus hendrerit bibendum. Nullam sed fermentum ante.</p>',
  'summary' => 'Nuestros expertos en viajes ofrecen  sus propias experiencias y conocimientos  en cada destino, no se trata sólo visitar...',
  'image' => 'img03.jpg',
);

$content_node[4] = array(
  'title' => 'Amabilidad',
  'body' => '<p>Estamos orgullosos de representar a los países aparecen en nuestro sitio y creemos que todos tienen una actitud amable y acogedora.</p>

<h3>Nuestro equipo</h3>
<p>Al hablar de nuestros expertos en viajes  siempre  encuentran esta actitud amable,  en todo el viaje siempre estarán dispuesto a ayudarte amablemente para descubrir estos grandes destinos. Hemos estado construyendo un servicio profesional basado en la cordialidad y el entendimiento.   En todas nuestras oficinas contamos con un  equipo experimentado que le guiarán y atenderán para satisfacerle en cada momento de su viaje.</p>

<h3>Hoteles que admitimos</h3>
<p>Entendemos que el alojamiento contribuyen a un viaje maravilloso, así que hemos trabajado duro para seleccionar una buena colección de hoteles y complejos turísticos  - sólo los que tienen un personal muy amable. Para todo proveedor que elegimos para viajar está garantizada, por nuestros expertos en viajes, una  actitud amable durante su estancia.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque in risus sed urna sollicitudin tincidunt ut vitae sapien. Duis aliquam magna at velit adipiscing, vel lobortis lorem bibendum. In rhoncus diam hendrerit accumsan tristique. Curabitur lobortis laoreet ligula quis varius. Vestibulum euismod egestas orci, quis venenatis arcu fringilla in. Suspendisse viverra, risus sed hendrerit adipiscing, ipsum justo commodo risus, vel tincidunt ante nunc ac orci. Morbi pharetra, dui eu fringilla luctus, diam diam semper nulla, ac suscipit dui nisi id odio. Cras fermentum nibh vel lacinia bibendum. Maecenas ornare ultricies ullamcorper. Suspendisse scelerisque vel elit at pulvinar. Nullam aliquet felis neque, quis vulputate augue malesuada ac. Proin lacinia lacus commodo mauris ornare ultrices id sit amet sapien. Aliquam vehicula in risus eget dictum. Sed euismod risus vitae adipiscing tincidunt. Proin ac nisi nulla.</p>',
  'summary' => 'Estamos orgullosos de representar a los países aparecen en nuestro sitio y creemos que todos tienen una actitud amable...',
  'image' => 'img04.jpg',
);

$content_node_article[0] = array(
  'title' => 'Turismo',
  'body' => '<p>Según la Organización Mundial del Turismo, el turismo comprende las actividades que realizan las personas durante sus viajes y estancias en lugares distintos al de su entorno habitual, por un período consecutivo inferior a un año y mayor a un día, con fines de ocio, por negocios o por otros motivos.</p>

<p>Arthur Bormann (Berlín, 1930) define el turismo como el conjunto de los viajes cuyo objeto es el placer o por motivos comerciales o profesionales y otros análogos, y durante los cuales la ausencia de la residencia habitual es temporal, no son turismo los viajes realizados para trasladarse al lugar de trabajo.</p>

<p>Walter Hunziker - Kurt Krapf, 1942 dicen que "El turismo es el conjunto de relaciones y fenómenos producidos por el desplazamiento y permanencia de personas fuera de su domicilio, en tanto que dichos desplazamientos y permanencia no están motivados por una actividad lucrativa".</p>

<p>El término "turismología" surgió en los años 60. Pero fue el yugoslavo Živadin Jovicic (geógrafo en su formación académica), el científico considerado "padre de la turismología", quién lo popularizó cuando fundó la revista del mismo nombre en 1972.</p>

<p>Jovicic consideraba que ninguna de las ciencias existentes podía realizar el estudio del turismo en toda su dimensión (ni la geografía, ni la economía, ni la sociología, etc.) por considerar que sus aportaciones son unilaterales. Esto lo permitiría la creación de una ciencia independiente, la turismología.</p>

<p>Tras recuperarse lentamente de los efectos de la recesión económica de 2008-2009, la cual fue agravada todavía más en algunas regiones debido al brote de la gripe A (H1N1) de 2009,4 5 6 las llegadas de turistas internacionales alcanzaron un récord de más de 1.000 milliones de turistas por primera vez en la historia en 2012.7 China fue el país cuyos ciudadanos realizaron los mayores gastos en turismo internacional en 2012, alcanzando USD 102 mil millones, superando a Alemania y los Estados Unidos, países que por varios años ocuparon los primeros lugares. China y los mercados emergentes han incrementado en forma significativa sus gastos en turismo, con Rusia y Brasil como ejemplos destacados que han subido varias posiciones en la clasificación de países que más gastan en turismo en el exterior.</p>

<p>Fuente: Wikipedia</p>',
);
$content_node_page[0] = array(
  'title' => '¿Qué es TOA b2c?',
  'body' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras et consequat tellus. Nunc euismod vehicula consequat. Cras id est consequat, ullamcorper enim et, posuere urna. Mauris cursus ullamcorper elementum. Aliquam dignissim nibh sed metus pretium, non blandit urna fermentum. Etiam venenatis, ligula eget porttitor molestie, ante lacus hendrerit mi, eget fringilla augue lorem in metus. Curabitur ut semper odio. Donec vulputate metus tortor, imperdiet ullamcorper dui tincidunt et.</p>',
);
$content_node_page[1] = array(
  'title' => '¿Qué es Travel Open Apps?',
  'body' => '<p>Travel Open Apps representa un ambicioso proyecto destinado a mejorar la capacidad del sector turístico de la Comunitat Valenciana en la creación, comercialización y distribución del producto turístico de la Comunitat Valenciana, utilizando todo el potencial que nos ofrecen las nuevas tecnologías. El proyecto apuesta por la gestión íntegra de la cadena de valor por los propios agentes del sector, siendo la administración la proveedora de la herramienta y garante de su acceso, utilidad y uso. - See more at: http://www.travelopenapps.org/que-es-travel-open-apps/#sthash.GXtpBwLZ.dpuf</p>
<p>Travel Open Apps está enfocado tanto a empresas como a destinos, en el que ambos encontrarán la posibilidad de hacer visible todo el potencial de su producto y distribuirlo o comunicarlo adecuadamente a sus segmentos y clientes. - See more at: http://www.travelopenapps.org/que-es-travel-open-apps/#sthash.GXtpBwLZ.dpuf</p>
<p>Travel Open Apps es un proyecto tecnológico y estratégico que permite acceder a todo el inventario de la Comunitat Valenciana y así generar combinaciones de productos de alto valor para el cliente final. De este modo son los mismos actores y agentes del sector los que, como verdaderos conocedores de sus destinos y segmentos, crean, comunican y distribuyen su producto por los canales de su elección. - See more at: http://www.travelopenapps.org/que-es-travel-open-apps/#sthash.GXtpBwLZ.dpuf</p>
<p>Además es un proyecto vivo, en constante cambio y proceso de mejora, porque es el sector el que va a hacerlo evolucionar tanto desde el punto de vista tecnológico, a través de la comunidad de desarrolladores, como estratégico, con el uso e implicación de todo el sector en el proyecto. - See more at: http://www.travelopenapps.org/que-es-travel-open-apps/#sthash.GXtpBwLZ.dpuf</p>
<p>Travel Open Apps provee al usuario de acceso a todo el inventario turístico de la Comunitat Valenciana y de la tecnología para aquellos facilitar las conexiones entre las empresas turísticas y los canales de distribución existentes. Con estos recursos el sector tiene las herramientas necesarias para construir productos adecuados para sus segmentos, capacidad para comercializar en las plataformas adecuadas y la posibilidad de distribuir por todos los canales existentes. - See more at: http://www.travelopenapps.org/que-es-travel-open-apps/#sthash.GXtpBwLZ.dpuf</p>
<p>Finalmente, ofrece una serie de recursos de gestión que permiten sacar el máximo partido a nuestra tecnología. Así, el usuario puede elegir entre su propio PMS o tomar el que le ofrece la herramienta, y puede crear sus propias páginas web, mejorar la relación con sus clientes mediante herramientas de fidelización y Business Intelligence. - See more at: http://www.travelopenapps.org/que-es-travel-open-apps/#sthash.GXtpBwLZ.dpuf</p>',
);





